namespace Nut.Ioc
{
    public class NutIocConstants
    {
        public const string GeneratedClassName = "__AutogeneratedNutIocDependencies";
        public const string GeneratedClassInterfaceName = "IEnumerable<KeyValuePair<Type, Func<Func<Type, object>, object>>>";
    }
}